/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ghp10P8lguZ
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Login() {
  return (
    <div className="h-screen bg-gray-100 flex items-center justify-center px-5 py-5">
      <div className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col">
        <div className="mb-4">
          <h2 className="text-center font-bold text-2xl mb-5">Login</h2>
          <Label className="block text-grey-darker text-sm font-bold mb-2" htmlFor="email">
            Email
          </Label>
          <Input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker"
            id="email"
            placeholder="Enter your email"
            required
            type="text"
          />
        </div>
        <div className="mb-6">
          <Label className="block text-grey-darker text-sm font-bold mb-2" htmlFor="password">
            Password
          </Label>
          <Input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker"
            id="password"
            placeholder="Enter your password"
            required
            type="password"
          />
        </div>
        <div className="flex items-center justify-between">
          <Button className="bg-blue-500 hover:bg-blue-dark text-white font-bold py-2 px-4 rounded" type="submit">
            Login
          </Button>
          <Link className="inline-block align-baseline font-bold text-sm text-blue hover:text-blue-darker" href="#">
            Forgot Password?
          </Link>
        </div>
        <hr className="my-6 border-t" />
        <div className="flex justify-center">
          <Button className="bg-red-500 hover:bg-red-dark text-white font-bold py-2 px-4 rounded" variant="outline">
            Google
          </Button>
          <Button
            className="bg-blue-500 hover:bg-blue-dark text-white font-bold py-2 px-4 rounded ml-2"
            variant="outline"
          >
            Facebook
          </Button>
          <Button className="bg-black hover:bg-gray-dark text-white font-bold py-2 px-4 rounded ml-2" variant="outline">
            Apple
          </Button>
        </div>
      </div>
    </div>
  )
}
